# Generated by Django 2.1.4 on 2018-12-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.IntegerField(default=1000, verbose_name='Ranking'),
        ),
    ]
