# Generated by Django 2.1.4 on 2018-12-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klask', '0002_auto_20181204_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.FloatField(default=1000.0, verbose_name='Ranking'),
        ),
        migrations.AlterField(
            model_name='playerhistory',
            name='rating',
            field=models.FloatField(verbose_name='Ranking'),
        ),
    ]
